language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - wget https://scrutinizer-ci.com/ocular.phar
  - php composer.phar --prefer-source --dev install
  - cp phpunit.xml.dist phpunit.xml

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ./ --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
